-- 1.
SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY AS "계열" FROM TB_DEPARTMENT;

-- 2.
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다' FROM TB_DEPARTMENT;

-- 3.
SELECT S.STUDENT_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON D.DEPARTMENT_NO = S.DEPARTMENT_NO
WHERE D.DEPARTMENT_NAME = '국어국문학과' AND SUBSTR(S.STUDENT_SSN, 8, 1) = 2 AND S.ABSENCE_YN = 'Y';

-- 4.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;

-- 5.
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7.
SELECT *
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8.
-- 데이터가 좀 이상함
SELECT C1.CLASS_NO, C1.CLASS_NAME, C1.PREATTENDING_CLASS_NO, C2.CLASS_NAME
FROM TB_CLASS C1
JOIN TB_CLASS C2 ON C1.PREATTENDING_CLASS_NO = C2.CLASS_NO
WHERE C1.PREATTENDING_CLASS_NO IS NOT NULL;

-- 9.
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT
ORDER BY CATEGORY ASC;

-- 10.
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE (ENTRANCE_DATE BETWEEN '02/01/01' AND '02/12/31') AND STUDENT_ADDRESS LIKE '전주%' AND ABSENCE_YN = 'N';
-- EXTRACT(YEAR FROM ENTRANCE_DATE) = 2002




-- 1.
SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "이름", TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') AS "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;

-- 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

-- 3.
SELECT PROFESSOR_NAME AS "교수이름", TO_CHAR(SYSDATE, 'YYYY')-CONCAT(19, SUBSTR(PROFESSOR_SSN, 1, 2)) AS "나이"
FROM TB_PROFESSOR
ORDER BY 나이;

-- 4.
SELECT SUBSTR(PROFESSOR_NAME,2,4) AS "이름"
FROM TB_PROFESSOR;

-- 5.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE TO_CHAR(ENTRANCE_DATE, 'YYYY') - CONCAT(19, SUBSTR(STUDENT_SSN, 1, 2)) > 19;

-- 6.
SELECT TO_CHAR(TO_DATE('20211225'), 'DAY') AS "2021년 크리스마스 요일" FROM DUAL;

-- 7.
SELECT TO_DATE('99/10/11', 'YYYY/MM/DD') FROM DUAL;
SELECT TO_DATE('99/10/11', 'RR/MM/DD') FROM DUAL;
SELECT TO_DATE('49/10/11', 'YY/MM/DD') FROM DUAL;
SELECT TO_DATE('49/10/11', 'RR/MM/DD') FROM DUAL;

SELECT TO_CHAR(TO_DATE('99/10/11'), 'YYYY/MM/DD') FROM DUAL;
SELECT TO_CHAR(TO_DATE('99/10/11'), 'RRRR/MM/DD') FROM DUAL;
SELECT TO_CHAR(TO_DATE('49/10/11'), 'RRRR/MM/DD') FROM DUAL;
SELECT TO_CHAR(TO_DATE('49/10/11'), 'YYYY/MM/DD') FROM DUAL;

-- 8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) <2000;

-- 9.
--SELECT S.STUDENT_NAME, G.POINT
--FROM TB_GRADE G
--JOIN TB_CLASS C ON G.CLASS_NO = C.CLASS_NO
--JOIN TB_STUDENT S ON G.STUDENT_NO = S.STUDENT_NO
--WHERE S.STUDENT_NO = 'A517178';

SELECT ROUND(AVG(G.POINT),1)
FROM TB_GRADE G
JOIN TB_CLASS C ON G.CLASS_NO = C.CLASS_NO
JOIN TB_STUDENT S ON G.STUDENT_NO = S.STUDENT_NO
GROUP BY S.STUDENT_NAME
HAVING S.STUDENT_NAME = '한아름';




SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;



SELECT * FROM TB_PROFESSOR








