CREATE TABLE QNA(
    BNO NUMBER,
    TITLE VARCHAR2(150) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    WRITER VARCHAR2(50) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    READCOUNT NUMBER DEFAULT 0,
    CONSTRAINT PK_QNA PRIMARY KEY(BNO)
);

COMMENT ON COLUMN QNA.BNO IS 'QNA 번호';
COMMENT ON COLUMN QNA.TITLE IS 'QNA 제목';
COMMENT ON COLUMN QNA.CONTENT IS 'QNA 내용';
COMMENT ON COLUMN QNA.WRITER IS 'QNA 작성자';
COMMENT ON COLUMN QNA.REG_DATE IS 'QNA 등록일';
COMMENT ON COLUMN QNA.MODIFY_DATE IS 'QNA 수정일';
COMMENT ON COLUMN QNA.READCOUNT IS 'QNA 조회수';

CREATE SEQUENCE SEQ_QNA_NO;

-- 테스트용
BEGIN
    FOR N IN 1..285
    LOOP
        INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '질문 제목' || SEQ_QNA_NO.CURRVAL, '질문 내용 ' || SEQ_QNA_NO.CURRVAL , '작가' ||  SEQ_QNA_NO.CURRVAL, DEFAULT, DEFAULT, DEFAULT);
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;

--DROP TABLE QNA;
--DROP SEQUENCE SEQ_QNA_NO;

------------------------------------------------
-- 댓글
CREATE TABLE REPLY (
    RNO NUMBER NOT NULL PRIMARY KEY,
    BNO NUMBER NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL,
    WRITER VARCHAR2(50) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE REPLY ADD CONSTRAINT FK_QNA FOREIGN KEY(BNO) REFERENCES QNA(BNO);

COMMENT ON COLUMN REPLY.RNO IS '댓글 번호';
COMMENT ON COLUMN REPLY.BNO IS '게시글 번호';
COMMENT ON COLUMN REPLY.WRITER IS '내용';
COMMENT ON COLUMN REPLY.CONTENT IS '작성자';
COMMENT ON COLUMN REPLY.TEG_DATE IS '작성일';
COMMENT ON COLUMN REPLY.MODIFY_DATE IS '수정일';

CREATE SEQUENCE SEQ_REPLY_NO;

COMMIT;

---댓글 테스트
INSERT INTO REPLY(BNO, RNO, CONTENT, WRITER) VALUES(285, SEQ_REPLY_NO.NEXTVAL, '테스트댓글1', '테스트 작성자1');

SELECT RNO, CONTENT, WRITER, REG_DATE FROM REPLY WHERE BNO = 285;

