CREATE TABLE SCHEDULE (
    NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER,
    SUBJECT VARCHAR2(50) NOT NULL,
    START_DATE VARCHAR2(30) NOT NULL,
    END_DATE VARCHAR2(30) NOT NULL,
    MEMO VARCHAR2(1000) NOT NULL,
    COLOR VARCHAR2(20) NOT NULL
);

ALTER TABLE SCHEDULE ADD CONSTRAINT FK_MEMBER FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO);

CREATE SEQUENCE SEQ_SCHEDULE_NO;

INSERT INTO SCHEDULE(NO,MEMBER_NO,SUBJECT,START_DATE,END_DATE,MEMO,COLOR)
VALUES
(SEQ_SCHEDULE_NO.NEXTVAL,2,'YOU','2022-03-15','2022-03-17','HI','#9775fa');

INSERT INTO SCHEDULE(NO,MEMBER_NO,SUBJECT,START_DATE,END_DATE,MEMO,COLOR)
VALUES
(SEQ_SCHEDULE_NO.NEXTVAL,3,'YOU','2022-03-18','2022-03-20','HI','#9775fa');

INSERT INTO SCHEDULE(NO,MEMBER_NO,SUBJECT,START_DATE,END_DATE,MEMO,COLOR)
VALUES
(SEQ_SCHEDULE_NO.NEXTVAL,2,'YOU','2022-03-19','2022-03-23','HI','#9775fa');



DROP TABLE SCHEDULE;

DROP SEQUENCE SEQ_SCHEDULE_NO;