CREATE TABLE MEMBER (
    NO NUMBER PRIMARY KEY,
    ID VARCHAR2(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(10) DEFAULT 'ROLE_USER',
    NAME VARCHAR2(15) NOT NULL,
    BIRTH VARCHAR2(15),
    NICKNAME VARCHAR2(15),
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(13),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN MEMBER.NO IS '회원번호';
COMMENT ON COLUMN MEMBER.ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.PASSWORD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.ROLE IS '회원타입';
COMMENT ON COLUMN MEMBER.NAME IS '회원명';
COMMENT ON COLUMN MEMBER.BIRTH IS '회원생일';
COMMENT ON COLUMN MEMBER.NICKNAME IS '회원별명';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '정보수정일';

CREATE SEQUENCE SEQ_UNO;

INSERT INTO MEMBER (
    NO, 
    ID, 
    PASSWORD, 
    ROLE,
    NAME,
    BIRTH,
    NICKNAME, 
    EMAIL,
    PHONE,
    STATUS, 
    ENROLL_DATE, 
    MODIFY_DATE
) VALUES(
    SEQ_UNO.NEXTVAL, 
    'admin2', 
    '1234', 
    'ROLE_ADMIN', 
    '관리자',
    '1800-01-01',
    '바비',
    'admin@iei.or.kr',
    '010-7777-1111',
    DEFAULT,
    DEFAULT,
    DEFAULT
);

COMMIT;

DROP TABLE MEMBER;
DROP SEQUENCE SEQ_UNO;


-- 공지테이블 작성 쿼리문 
CREATE TABLE NOTICE (	
    NOTICE_NO NUMBER,
    WRITER_NO NUMBER, 
	NOTICE_TITLE VARCHAR2(100), 
	NOTICE_CONTENT VARCHAR2(4000), 
	READCOUNT NUMBER DEFAULT 0, 
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    CREATE_DATE DATE DEFAULT SYSDATE, 
    MODIFY_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_NOTICE_NO PRIMARY KEY(NOTICE_NO),
    CONSTRAINT FK_NOTICE_WRITER FOREIGN KEY(WRITER_NO) REFERENCES MEMBER(NO) ON DELETE SET NULL
);



COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지번호';
COMMENT ON COLUMN NOTICE.WRITER_NO IS '작성자';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지내용';
COMMENT ON COLUMN NOTICE.READCOUNT IS '조회수';
COMMENT ON COLUMN NOTICE.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN NOTICE.CREATE_DATE IS '공지등록일';
COMMENT ON COLUMN NOTICE.MODIFY_DATE IS '공지수정일';

CREATE SEQUENCE SEQ_NOTICE_NO;

-- 공지 테이블 삭제 명령어↓
--DROP TABLE NOTICE;
--DROP SEQUENCE SEQ_NOTICE_NO;
--SELECT SEQ_NOTICE_NO.CURRVAL FROM DUAL;

INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '유캠프 운영정책 안내',  '운영정책에 대해서 말씀드립니다.', DEFAULT, 'Y', SYSDATE, SYSDATE);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '안전거래 캠페인에 따른 공지',  '안전거래 캠페인에 대해서 말씀드립니다.', DEFAULT, 'Y', SYSDATE, SYSDATE);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '게시판 거래 정책 안내',  '게시판 거래 정책에 대해서 말씀드립니다.', DEFAULT, 'Y', SYSDATE, SYSDATE);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '개인정보처리방침',  '개인정보 처리방침에 대해서 말씀드립니다.', DEFAULT, 'Y', SYSDATE, SYSDATE);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '지역광고 후기 이벤트 당첨자를 공개해요!',  '지역광고 후기 이벤트 당첨자를 공개합니다. 당첨자는...감자킹님입니다!', DEFAULT, 'Y', SYSDATE, SYSDATE);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '[이벤트] 반려동물과 함께 캠핑을 즐기자!',  '반려동물과 함께 캠핑을 즐기자! 이벤트 안내입니다.', DEFAULT, 'Y', SYSDATE, SYSDATE);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '[공지] 새해에도 행복한 일 가득하세요!',  '새해맞이 인사드립니다. <br>다들 행복한 새해되세요. ', DEFAULT, 'Y', SYSDATE, SYSDATE);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '[이벤트] 새해맞이 복주머니 찾기',  '새해맞이 복주머니 이벤트 진행예정입니다. <br><br>사이트에 숨어있는 복주머니를 찾아주세요!<br>기간은 1월 31일까지입니다. ', DEFAULT, 'Y', SYSDATE, SYSDATE);

COMMIT;

DROP TABLE NOTICE;
DROP SEQUENCE SEQ_NOTICE_NO;

SELECT RNUM, NOTICE_NO, NOTICE_TITLE, CREATE_DATE, STATUS
FROM (
    SELECT ROWNUM AS RNUM, NOTICE_NO, NOTICE_TITLE, CREATE_DATE, STATUS
    FROM (
        SELECT  NOTICE_NO, NOTICE_TITLE, CREATE_DATE, STATUS
        FROM NOTICE
        WHERE STATUS = 'Y'  ORDER BY NOTICE_NO DESC
    )
)
WHERE RNUM BETWEEN 11 and 20;